# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 697)
        MainWindow.setMinimumSize(QtCore.QSize(550, 550))
        MainWindow.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(35, 35))
        self.frame_10.setMaximumSize(QtCore.QSize(35, 35))
        self.frame_10.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_9)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 23)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_8.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ECEFF4;")
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setStyleSheet("color: #2E3440;")
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        self.label_3.setMinimumSize(QtCore.QSize(250, 0))
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #2E3440;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #2E3440;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #2E3440;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(14, 29, 53);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"color: rgb(21, 21, 21);\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeBtn = QtWidgets.QPushButton(self.frame_7)
        self.minimizeBtn.setMinimumSize(QtCore.QSize(0, 35))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.minimizeBtn.setStyleSheet("QPushButton {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.minimizeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../EziPDF Responsive/Master/images/icons/cil-window-minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeBtn.setIcon(icon)
        self.minimizeBtn.setIconSize(QtCore.QSize(16, 16))
        self.minimizeBtn.setFlat(True)
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_2.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.frame_7)
        self.restoreBtn.setMinimumSize(QtCore.QSize(0, 35))
        self.restoreBtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.restoreBtn.setStyleSheet("QPushButton {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.restoreBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../EziPDF Responsive/Master/images/icons/cil-window-restore.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restoreBtn.setIcon(icon1)
        self.restoreBtn.setIconSize(QtCore.QSize(16, 16))
        self.restoreBtn.setFlat(True)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_2.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame_7)
        self.closeBtn.setMinimumSize(QtCore.QSize(0, 35))
        self.closeBtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.closeBtn.setStyleSheet("QPushButton {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../EziPDF Responsive/Master/images/icons/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setIconSize(QtCore.QSize(16, 16))
        self.closeBtn.setFlat(True)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.verticalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(-1, 51, -1, -1)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_3.setMaximumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_5.setMaximumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_4.setMaximumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_7.setMaximumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.verticalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(-1, 60, 0, 0)
        self.verticalLayout_5.setSpacing(25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(125, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(125, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMinimumSize(QtCore.QSize(125, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(125, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #2E3440;\n"
"color: #ECEFF4;\n"
"border-radius: 0px;\n"
"bored: 0px solid;\n"
"text-align: left;\n"
"padding: 2px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(127, 173, 255);\n"
"color: #2E3440;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 44, 52);\n"
"color: #4C566A;\n"
"}")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 179, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.size_grip = QtWidgets.QFrame(self.frame_5)
        self.size_grip.setMinimumSize(QtCore.QSize(25, 25))
        self.size_grip.setMaximumSize(QtCore.QSize(25, 25))
        self.size_grip.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.size_grip.setObjectName("size_grip")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.size_grip)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.size_grip)
        self.pushButton_8.setStyleSheet("color: blue;")
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/cil-size-grip.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_9.addWidget(self.pushButton_8)
        self.verticalLayout_5.addWidget(self.size_grip, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "PDF COMBINE - DESKTOP UTILITY"))
        self.label.setText(_translate("MainWindow", "Drag & Drop PDF Files or Upload:"))
        self.label_3.setText(_translate("MainWindow", "File Name"))
        self.label_5.setText(_translate("MainWindow", "Location"))
        self.label_4.setText(_translate("MainWindow", "Size"))
        self.pushButton_3.setText(_translate("MainWindow", "     UPLOAD"))
        self.pushButton_5.setText(_translate("MainWindow", "    MOVE UP"))
        self.pushButton.setText(_translate("MainWindow", " MOVE DOWN"))
        self.pushButton_4.setText(_translate("MainWindow", "    REMOVE"))
        self.pushButton_7.setText(_translate("MainWindow", "      CLEAR"))
        self.pushButton_6.setText(_translate("MainWindow", "COMBINE PDF"))
        self.pushButton_2.setText(_translate("MainWindow", "    SAVE AS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
